service: cst-api

provider:
  name: aws
  runtime: nodejs8.10

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::compression-space-transport/*" ] ]  }

functions:
  getAllLeases:
    handler: leases.getAll
    events:
      - http:
          response:
            body:
              Content-Type: "'application.json'"
          integration: lambda
          authorizer:
            name: authorizer
            arn: ${env:COGNITO_ARN}
            claims:
              - email
          path: leases/all
          method: get

  getLatestLeases:
    handler: leases.getLatest
    events:
      - http:
          response:
            body:
              Content-Type: "'application.json'"
          integration: lambda
          authorizer:
            name: authorizer
            arn: ${env:COGNITO_ARN}
            claims:
              - email
          path: leases/latest
          method: get

  getOnlineLeases:
    handler: leases.getOnline
    events:
      - http:
          response:
            body:
              Content-Type: "'application.json'"
          integration: lambda
          authorizer:
            name: authorizer
            arn: ${env:COGNITO_ARN}
            claims:
              - email
          path: leases/online
          method: get

  getLeaseStatusForMac:
    handler: leases.getStatusForMac
    events:
      - http:
          response:
            body:
              Content-Type: "'application.json'"
          integration: lambda
          authorizer:
            name: authorizer
            arn: ${env:COGNITO_ARN}
            claims:
              - email
          path: leases/device/{mac}/status
          method: get
          request:
            parameters:
              paths:
                mac: true

  getInterfaceConfig:
    handler: ifconfig.getInterface
    events:
      - http:
          response:
            body:
              Content-Type: "'application.json'"
          integration: lambda
          authorizer:
            name: authorizer
            arn: ${env:COGNITO_ARN}
            claims:
              - email
          path: network/interfaces/{ifName}
          method: get
          request:
            parameters:
              paths:
                ifName: true

  getSystemStats:
    handler: stats.getSystem
    events:
      - http:
          response:
            body:
              Content-Type: "'application.json'"
          integration: lambda
          authorizer:
            name: authorizer
            arn: ${env:COGNITO_ARN}
            claims:
              - email
          path: system/stats
          method: get

  getIptstate:
    handler: stats.getIptstate
    events:
      - http:
          response:
            body:
              Content-Type: "'application.json'"
          integration: lambda
          authorizer:
            name: authorizer
            arn: ${env:COGNITO_ARN}
            claims:
              - email
          path: network/iptstate
          method: get
